#!/bin/bash
# This script calculates simple interest given principle
# annual rate of interest and time period in years.

# Do not use this in production. Sample purpose only.

Author: Upkar Lidder (IBM)
Additional Authors: 
<fisherback>

echo "Enter the principle:"
read p
echo "Enter rate of interest:"
read r
echo "Time of period in years:"
read t
s= 'expr $p\*$t\*$r/
echo "The simple interest is:"
echo $s
